export const GET_BRANDS_MASTER = 'GET_BRANDS_MASTER'
export const GET_BRANDS_MASTER_SUCCESS = 'GET_BRANDS_MASTER_SUCCESS'
export const CREATE_BRAND_MASTER = 'CREATE_BRAND_MASTER'
export const UPDATE_BRAND_MASTER = 'UPDATE_BRAND_MASTER'
export const DELETE_BRAND_MASTER = 'DELETE_BRAND_MASTER'

export const GET_VENDORS_MASTER = 'GET_VENDORS_MASTER'
export const GET_VENDORS_MASTER_SUCCESS = 'GET_VENDORS_MASTER_SUCCESS'
export const CREATE_VENDOR_MASTER = 'CREATE_VENDOR_MASTER'
export const UPDATE_VENDOR_MASTER = 'UPDATE_VENDOR_MASTER'
export const DELETE_VENDOR_MASTER = 'DELETE_VENDOR_MASTER'

export const GET_DESTINATIONS_MASTER = 'GET_DESTINATION_MASTER'
export const GET_DESTINATIONS_MASTER_SUCCESS = 'GET_DESTINATION_MASTER_SUCCESS'
export const CREATE_DESTINATION_MASTER = 'CREATE_DESTINATION_MASTER'
export const UPDATE_DESTINATION_MASTER = 'UPDATE_DESTINATION_MASTER'
export const DELETE_DESTINATION_MASTER = 'DELETE_VENDOR_MASTER'

export const GET_OTHERS_MASTER = 'GET_OTHERS_MASTER'
export const GET_OTHERS_MASTER_SUCCESS = 'GET_OTHERS_MASTER_SUCCESS'
export const CREATE_OTHER_MASTER = 'CREATE_OTHER_MASTER'
export const UPDATE_OTHER_MASTER = 'UPDATE_OTHER_MASTER'
export const DELETE_OTHER_MASTER = 'DELETE_OTHER_MASTER'

export const GET_TRUCKS_MASTER = 'GET_TRUCKS_MASTER'
export const GET_TRUCKS_MASTER_SUCCESS = 'GET_TRUCKS_MASTER_SUCCESS'
export const CREATE_TRUCK_MASTER = 'CREATE_TRUCK_MASTER'
export const UPDATE_TRUCK_MASTER = 'UPDATE_TRUCK_MASTER'
export const DELETE_TRUCK_MASTER = 'DELETE_TRUCK_MASTER'

export const GET_STAYING_TRUCKS = 'GET_STAYING_TRUCKS'
export const GET_STAYING_TRUCKS_SUCCESS = 'GET_STAYING_TRUCKS_SUCCESS'
export const CREATE_STAYING_TRUCK = 'CREATE_STAYING_TRUCK'
export const UPDATE_STAYING_TRUCK = 'UPDATE_STAYING_TRUCK'
export const DELETE_STAYING_TRUCK = 'DELETE_STAYING_TRUCK'

export const GET_ITEM_OPERATION_SETTING = 'GET_ITEM_OPERATION_SETTING'
export const GET_ITEM_OPERATION_SETTING_SUCCESS =
  'GET_ITEM_OPERATION_SETTING_SUCCESS'
export const UPDATE_ITEM_OPERATION_SETTING = 'UPDATE_ITEM_OPERATION_SETTING'

export const GET_MEASUREMENT_DATA_LIST = 'GET_MEASUREMENT_DATA_LIST'
export const GET_MEASUREMENT_DATA_LIST_SUCCESS =
  'GET_MEASUREMENT_DATA_LIST_SUCCESS'
export const UPDATE_MEASUREMENT_DATA_LIST = 'UPDATE_MEASUREMENT_DATA_LIST'
export const DELETE_MEASUREMENT_DATA_LIST = 'DELETE_MEASUREMENT_DATA_LIST'

export const CREATE_WEIGHING = 'CREATE_WEIGHING'
export const UPDATE_WEIGHING = 'UPDATE_WEIGHING'
export const GET_MAX_SLIPNO = 'GET_MAX_SLIPNO'

export const GET_WEIGHING_OPERATION_SETTING = 'GET_WEIGHING_OPERATION_SETTING'
export const GET_WEIGHING_OPERATION_SETTING_SUCCESS =
  'GET_WEIGHING_OPERATION_SETTING_SUCCESS'
export const UPDATE_WEIGHING_OPERATION_SETTING =
  'UPDATE_WEIGHING_OPERATION_SETTING'
export const GET_SERIAL_PORTS = 'GET_SERIAL_PORTS'

export const GET_SUMMARY_REPORT = 'GET_SUMMARY_REPORT'
export const GET_SUMMARY_REPORT_SUCCESS = 'GET_SUMMARY_REPORT_SUCCESS'

export const GET_USB_DRIVES = 'GET_USB_DRIVES'
